fix(e2e): explicitly name files with commonjs ending, due to jest error
ReferenceError: Jest: Got error running globalSetup - /home/runner/work/data-modules/data-modules/contacts/src/e2e-tests/globalSetup.js, reason: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/data-modules/data-modules/contacts/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.

see: https://github.com/solid-contrib/data-modules/actions/runs/17923096550/job/50962626248#step:8:9